### PR TITLE
rebuild to remove cryptography upper bound

### PR DESCRIPTION
**Pull request by cbouss**
Changes:
- update about section
- remove noarch
- add tests

https://github.com/oauthlib/oauthlib/tree/v3.2.0

### CODE REVIEW

**Comment by skupriienko** [comment]
I guess it's not good idea to bump build number and remove noarch python. We can rebuild it as noarch as an exception

**Review by varlackc — COMMENTED** [review]
The `doc_url` seems to have a redirect to the following direction:
https://oauthlib.readthedocs.io/en/latest/

**Comment by cbouss** [comment]
> I guess it's not good idea to bump build number and remove noarch python. We can rebuild it as noarch as an exception

That makes sense, I have reverted to noarch.

**Comment by cbouss** [comment]
> The `doc_url` seems to have a redirect to the following direction: https://oauthlib.readthedocs.io/en/latest/

Thank you, updated.

**Pull request merged**
